### ISSUE TITLE
How to Increase Communication Range?

### ISSUE THREAD

**Issue by pjake12** [Agr-IoT/LEACH#10]
I tried using *.host*.wlan[0].radio.transmitter.communicationRange however it does not work.

**Comment by n-jay** [comment]
The `host.wlan[0].radio.transmitter.communicationRange` is a parameter that ingests a boolean value. It is used to show the communication range circles when running in Qtenv configuration (the GUI).

Since we're using the `ApskScalarRadio` module for the radio, the communication range is going to be set by varying parameters like `sensitivity`, `energyDetection` and `snirThreshold`.
