### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pjake12** [Agr-IoT/LEACH#3]
Good Day,

#2 still happens even though I have linked LEACH3 to INET and have rebuilt both INET and LEACH3 project files.

Thank you.

![error](https://user-images.githubusercontent.com/117272839/199919496-68a201c0-524f-4430-b045-935dc9a296e3.PNG)

**Comment by RomainBerthomieu** [comment]
Hello,
Clang does not work on Windows. Try to set, in "configure.user", PREFFER_CLANG=no ; then uncomment CC=gcc
Then, in the terminal opened by mingwenv.cmd, type:
$ ./configure
$ make clean
$ make

**Comment by pjake12** [comment]
Hello @RomainBerthomieu 

I tried doing this but it still won't run. What is clang and what OS is clang compatible with?

Thank you.

**Comment by RomainBerthomieu** [comment]
@pjake12 I tried running Omnet++ on Linux, but I feel like it's a little nightmare. I strongly recommand staying on Windows.

One other issue with this code is the lack of the function stop(), I don't remember in which .cc file, it surely will tell you which file in the error.

Simply write ```void {name_of_.cc_file}::stop(){}``` where it's relevent.
For example, if it's in the Leach.cc, it would become ```void Leach::stop(){}```.

Feel free to post a screenshot of the error if it's not related to that, I might be able to help.

**Comment by n-jay** [comment]
> I tried doing this but it still won't run. 

 @pjake12, based on my experience, linking to INET and rebuilding should work. 

Please ensure all steps in the README are properly followed:

> 4. Copy the LEACHnode and leach directories present in the node and routing directories respectively to the node and routing directories in the your installed INET project. 
> 5. Import the LEACH3 project into the workspace via Existing project into Workspace option. Link it with INET using properties project references and ticking on the inet option.

Keep in mind, you have to build INET first and then the LEACH3 directory. I recommend building INET and then importing LEACH3, linking it and rebuilding.

> What is clang and what OS is clang compatible with?

Clang is a compiler for C++. It is compatible with all OSs capable of running C++, to my knowledge.

> I tried running Omnet++ on Linux, but I feel like it's a little nightmare. I strongly recommend staying on Windows.

@RomainBerthomieu up to this point I've exclusively worked with Omnet++ on Linux. After the initial setup following the [documentation](https://doc.omnetpp.org/omnetpp/InstallGuide.pdf), everything has worked fine.

> One other issue with this code is the lack of the function stop(), I don't remember in which .cc file, it surely will tell you which file in the error.

I've not included the `stop` function in my code as I've not needed it since I run the simulation for a finite duration.
You are free to add it as required.
